"""Rename useDescription to description

Revision ID: 2480396cb89a
Revises: 
Create Date: 2025-10-22 16:34:20.535185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2480396cb89a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('description', sa.Text(), nullable=False, comment='사용자 설명'))
    op.drop_column('users', 'useDescription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('useDescription', mysql.TEXT(), nullable=False, comment='사용자 설명'))
    op.drop_column('users', 'description')
    # ### end Alembic commands ###

